version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: INVENT_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: INVENT_DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"